const std = @import("std");
const builtin = @import("builtin");
const build_options = @import("build_options");
pub const c = @cImport({
    // https://github.com/Games-by-Mason/tracy_zig/blob/main/src/impl_enabled.zig
    // https://github.com/cipharius/zig-tracy/blob/master/src/tracy.zig
    if (build_options.tracy_enable) @cDefine("TRACY_ENABLE", "");
    if (!build_options.tracy_callstack_enable) @cDefine("TRACY_NO_CALLSTACK", "1");
    if (build_options.tracy_default_callstack_depth) |callstack_depth| @cDefine("TRACY_CALLSTACK", "\"" ++ std.fmt.digits2(@intCast(callstack_depth)) ++ "\"");
    // if (build_options.tracy_on_demand) @cDefine("TRACY_ON_DEMAND", "");
    // if (build_options.tracy_no_broadcast) @cDefine("TRACY_NO_BROADCAST", "");
    // if (build_options.tracy_only_localhost) @cDefine("TRACY_ONLY_LOCALHOST", "");
    // if (build_options.tracy_only_ipv4) @cDefine("TRACY_ONLY_IPV4", "");
    // if (build_options.tracy_delayed_init) @cDefine("TRACY_DELAYED_INIT", "");
    // if (build_options.tracy_manual_lifetime) @cDefine("TRACY_MANUAL_LIFETIME", "");
    // if (build_options.tracy_verbose) @cDefine("TRACY_VERBOSE", "");
    // if (build_options.tracy_data_port) |p| @cDefine("TRACY_DATA_PORT", p);
    // if (build_options.tracy_broadcast_port) |p| @cDefine("TRACY_BROADCAST_PORT", p);
    @cInclude("tracy/tracy/TracyC.h");
});

comptime {
    if (build_options.tracy_enable and builtin.cpu.arch.endian() != .little)
        @compileError("Tracy supports only little-endian architectures.");
}

pub inline fn frameMark(name: ?[:0]const u8) void {
    if (build_options.tracy_enable) c.___tracy_emit_frame_mark(name);
}

pub inline fn frameMarkStart(name: [:0]const u8) void {
    if (build_options.tracy_enable) c.___tracy_emit_frame_mark_start(name);
}

pub inline fn frameMarkEnd(name: [:0]const u8) void {
    if (build_options.tracy_enable) c.___tracy_emit_frame_mark_end(name);
}

pub const Zone = struct {
    ctx: if (build_options.tracy_enable) c.TracyCZoneCtx else void,

    pub const BeginOptions = struct {
        name: ?[*:0]const u8 = null,
        src: std.builtin.SourceLocation,
        color: Color = .red,
        callstack_depth: ?u32 = build_options.tracy_default_callstack_depth,
    };

    pub inline fn begin(options: BeginOptions) @This() {
        return .{
            .ctx = if (build_options.tracy_enable) (if (options.callstack_depth) |callstack_depth|
                c.___tracy_emit_zone_begin_callstack(&.{
                    .name = options.name,
                    .function = options.src.fn_name,
                    .file = options.src.file,
                    .line = options.src.line,
                    .color = @bitCast(options.color),
                }, callstack_depth, 1)
            else
                c.___tracy_emit_zone_begin(&.{
                    .name = options.name,
                    .function = options.src.fn_name,
                    .file = options.src.file,
                    .line = options.src.line,
                    .color = @bitCast(options.color),
                }, 1)) else {},
        };
    }

    pub inline fn end(self: @This()) void {
        if (build_options.tracy_enable) c.___tracy_emit_zone_end(self.ctx);
    }

    pub inline fn setText(self: @This(), text: []const u8) void {
        if (build_options.tracy_enable) c.___tracy_emit_zone_text(self.ctx, text.ptr, text.len);
    }

    pub inline fn setName(self: @This(), name: []const u8) void {
        if (build_options.tracy_enable) c.___tracy_emit_zone_name(self.ctx, name.ptr, name.len);
    }

    pub inline fn setColor(self: @This(), color: u32) void {
        if (build_options.tracy_enable) c.___tracy_emit_zone_color(self.ctx, color);
    }

    pub inline fn setValue(self: @This(), value: u64) void {
        if (build_options.tracy_enable) c.___tracy_emit_zone_value(self.ctx, value);
    }
};

pub const Color = packed struct {
    b: u8,
    g: u8,
    r: u8,
    a: u8,

    pub const snow: @This() = .{ .r = 0xFA, .g = 0xFA, .b = 0xFF, .a = 0xFF };
    pub const ghost_white: @This() = .{ .r = 0xFF, .g = 0xF8, .b = 0xF8, .a = 0xFF };
    pub const white_smoke: @This() = .{ .r = 0xF5, .g = 0xF5, .b = 0xF5, .a = 0xFF };
    pub const gainsboro: @This() = .{ .r = 0xDC, .g = 0xDC, .b = 0xDC, .a = 0xFF };
    pub const floral_white: @This() = .{ .r = 0xF0, .g = 0xFA, .b = 0xFF, .a = 0xFF };
    pub const old_lace: @This() = .{ .r = 0xE6, .g = 0xF5, .b = 0xFD, .a = 0xFF };
    pub const linen: @This() = .{ .r = 0xE6, .g = 0xF0, .b = 0xFA, .a = 0xFF };
    pub const antique_white: @This() = .{ .r = 0xD7, .g = 0xEB, .b = 0xFA, .a = 0xFF };
    pub const papaya_whip: @This() = .{ .r = 0xD5, .g = 0xEF, .b = 0xFF, .a = 0xFF };
    pub const blanched_almond: @This() = .{ .r = 0xCD, .g = 0xEB, .b = 0xFF, .a = 0xFF };
    pub const bisque: @This() = .{ .r = 0xC4, .g = 0xE4, .b = 0xFF, .a = 0xFF };
    pub const peach_puff: @This() = .{ .r = 0xB9, .g = 0xDA, .b = 0xFF, .a = 0xFF };
    pub const navajo_white: @This() = .{ .r = 0xAD, .g = 0xDE, .b = 0xFF, .a = 0xFF };
    pub const moccasin: @This() = .{ .r = 0xB5, .g = 0xE4, .b = 0xFF, .a = 0xFF };
    pub const cornsilk: @This() = .{ .r = 0xDC, .g = 0xF8, .b = 0xFF, .a = 0xFF };
    pub const ivory: @This() = .{ .r = 0xF0, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const lemon_chiffon: @This() = .{ .r = 0xCD, .g = 0xFA, .b = 0xFF, .a = 0xFF };
    pub const seashell: @This() = .{ .r = 0xEE, .g = 0xF5, .b = 0xFF, .a = 0xFF };
    pub const honeydew: @This() = .{ .r = 0xF0, .g = 0xFF, .b = 0xF0, .a = 0xFF };
    pub const mint_cream: @This() = .{ .r = 0xFA, .g = 0xFF, .b = 0xF5, .a = 0xFF };
    pub const azure: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xF0, .a = 0xFF };
    pub const alice_blue: @This() = .{ .r = 0xFF, .g = 0xF8, .b = 0xF0, .a = 0xFF };
    pub const lavender: @This() = .{ .r = 0xFA, .g = 0xE6, .b = 0xE6, .a = 0xFF };
    pub const lavender_blush: @This() = .{ .r = 0xF5, .g = 0xF0, .b = 0xFF, .a = 0xFF };
    pub const misty_rose: @This() = .{ .r = 0xE1, .g = 0xE4, .b = 0xFF, .a = 0xFF };
    pub const white: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const black: @This() = .{ .r = 0x00, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const dark_slate_gray: @This() = .{ .r = 0x4F, .g = 0x4F, .b = 0x2F, .a = 0xFF };
    pub const dark_slate_grey: @This() = .{ .r = 0x4F, .g = 0x4F, .b = 0x2F, .a = 0xFF };
    pub const dim_gray: @This() = .{ .r = 0x69, .g = 0x69, .b = 0x69, .a = 0xFF };
    pub const dim_grey: @This() = .{ .r = 0x69, .g = 0x69, .b = 0x69, .a = 0xFF };
    pub const slate_gray: @This() = .{ .r = 0x90, .g = 0x80, .b = 0x70, .a = 0xFF };
    pub const slate_grey: @This() = .{ .r = 0x90, .g = 0x80, .b = 0x70, .a = 0xFF };
    pub const light_slate_gray: @This() = .{ .r = 0x99, .g = 0x88, .b = 0x77, .a = 0xFF };
    pub const light_slate_grey: @This() = .{ .r = 0x99, .g = 0x88, .b = 0x77, .a = 0xFF };
    pub const gray: @This() = .{ .r = 0xBE, .g = 0xBE, .b = 0xBE, .a = 0xFF };
    pub const grey: @This() = .{ .r = 0xBE, .g = 0xBE, .b = 0xBE, .a = 0xFF };
    pub const x11_gray: @This() = .{ .r = 0xBE, .g = 0xBE, .b = 0xBE, .a = 0xFF };
    pub const x11_grey: @This() = .{ .r = 0xBE, .g = 0xBE, .b = 0xBE, .a = 0xFF };
    pub const web_gray: @This() = .{ .r = 0x80, .g = 0x80, .b = 0x80, .a = 0xFF };
    pub const web_grey: @This() = .{ .r = 0x80, .g = 0x80, .b = 0x80, .a = 0xFF };
    pub const light_grey: @This() = .{ .r = 0xD3, .g = 0xD3, .b = 0xD3, .a = 0xFF };
    pub const light_gray: @This() = .{ .r = 0xD3, .g = 0xD3, .b = 0xD3, .a = 0xFF };
    pub const midnight_blue: @This() = .{ .r = 0x70, .g = 0x19, .b = 0x19, .a = 0xFF };
    pub const navy: @This() = .{ .r = 0x80, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const navy_blue: @This() = .{ .r = 0x80, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const cornflower_blue: @This() = .{ .r = 0xED, .g = 0x95, .b = 0x64, .a = 0xFF };
    pub const dark_slate_blue: @This() = .{ .r = 0x8B, .g = 0x3D, .b = 0x48, .a = 0xFF };
    pub const slate_blue: @This() = .{ .r = 0xCD, .g = 0x5A, .b = 0x6A, .a = 0xFF };
    pub const medium_slate_blue: @This() = .{ .r = 0xEE, .g = 0x68, .b = 0x7B, .a = 0xFF };
    pub const light_slate_blue: @This() = .{ .r = 0xFF, .g = 0x70, .b = 0x84, .a = 0xFF };
    pub const medium_blue: @This() = .{ .r = 0xCD, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const royal_blue: @This() = .{ .r = 0xE1, .g = 0x69, .b = 0x41, .a = 0xFF };
    pub const blue: @This() = .{ .r = 0xFF, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const dodger_blue: @This() = .{ .r = 0xFF, .g = 0x90, .b = 0x1E, .a = 0xFF };
    pub const deep_sky_blue: @This() = .{ .r = 0xFF, .g = 0xBF, .b = 0x00, .a = 0xFF };
    pub const sky_blue: @This() = .{ .r = 0xEB, .g = 0xCE, .b = 0x87, .a = 0xFF };
    pub const light_sky_blue: @This() = .{ .r = 0xFA, .g = 0xCE, .b = 0x87, .a = 0xFF };
    pub const steel_blue: @This() = .{ .r = 0xB4, .g = 0x82, .b = 0x46, .a = 0xFF };
    pub const light_steel_blue: @This() = .{ .r = 0xDE, .g = 0xC4, .b = 0xB0, .a = 0xFF };
    pub const light_blue: @This() = .{ .r = 0xE6, .g = 0xD8, .b = 0xAD, .a = 0xFF };
    pub const powder_blue: @This() = .{ .r = 0xE6, .g = 0xE0, .b = 0xB0, .a = 0xFF };
    pub const pale_turquoise: @This() = .{ .r = 0xEE, .g = 0xEE, .b = 0xAF, .a = 0xFF };
    pub const dark_turquoise: @This() = .{ .r = 0xD1, .g = 0xCE, .b = 0x00, .a = 0xFF };
    pub const medium_turquoise: @This() = .{ .r = 0xCC, .g = 0xD1, .b = 0x48, .a = 0xFF };
    pub const turquoise: @This() = .{ .r = 0xD0, .g = 0xE0, .b = 0x40, .a = 0xFF };
    pub const cyan: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const aqua: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const light_cyan: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xE0, .a = 0xFF };
    pub const cadet_blue: @This() = .{ .r = 0xA0, .g = 0x9E, .b = 0x5F, .a = 0xFF };
    pub const medium_aquamarine: @This() = .{ .r = 0xAA, .g = 0xCD, .b = 0x66, .a = 0xFF };
    pub const aquamarine: @This() = .{ .r = 0xD4, .g = 0xFF, .b = 0x7F, .a = 0xFF };
    pub const dark_green: @This() = .{ .r = 0x00, .g = 0x64, .b = 0x00, .a = 0xFF };
    pub const dark_olive_green: @This() = .{ .r = 0x2F, .g = 0x6B, .b = 0x55, .a = 0xFF };
    pub const dark_sea_green: @This() = .{ .r = 0x8F, .g = 0xBC, .b = 0x8F, .a = 0xFF };
    pub const sea_green: @This() = .{ .r = 0x57, .g = 0x8B, .b = 0x2E, .a = 0xFF };
    pub const medium_sea_green: @This() = .{ .r = 0x71, .g = 0xB3, .b = 0x3C, .a = 0xFF };
    pub const light_sea_green: @This() = .{ .r = 0xAA, .g = 0xB2, .b = 0x20, .a = 0xFF };
    pub const pale_green: @This() = .{ .r = 0x98, .g = 0xFB, .b = 0x98, .a = 0xFF };
    pub const spring_green: @This() = .{ .r = 0x7F, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const lawn_green: @This() = .{ .r = 0x00, .g = 0xFC, .b = 0x7C, .a = 0xFF };
    pub const green: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const lime: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const x11_green: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const web_green: @This() = .{ .r = 0x00, .g = 0x80, .b = 0x00, .a = 0xFF };
    pub const chartreuse: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0x7F, .a = 0xFF };
    pub const medium_spring_green: @This() = .{ .r = 0x9A, .g = 0xFA, .b = 0x00, .a = 0xFF };
    pub const green_yellow: @This() = .{ .r = 0x2F, .g = 0xFF, .b = 0xAD, .a = 0xFF };
    pub const lime_green: @This() = .{ .r = 0x32, .g = 0xCD, .b = 0x32, .a = 0xFF };
    pub const yellow_green: @This() = .{ .r = 0x32, .g = 0xCD, .b = 0x9A, .a = 0xFF };
    pub const forest_green: @This() = .{ .r = 0x22, .g = 0x8B, .b = 0x22, .a = 0xFF };
    pub const olive_drab: @This() = .{ .r = 0x23, .g = 0x8E, .b = 0x6B, .a = 0xFF };
    pub const dark_khaki: @This() = .{ .r = 0x6B, .g = 0xB7, .b = 0xBD, .a = 0xFF };
    pub const khaki: @This() = .{ .r = 0x8C, .g = 0xE6, .b = 0xF0, .a = 0xFF };
    pub const pale_goldenrod: @This() = .{ .r = 0xAA, .g = 0xE8, .b = 0xEE, .a = 0xFF };
    pub const light_goldenrod_yellow: @This() = .{ .r = 0xD2, .g = 0xFA, .b = 0xFA, .a = 0xFF };
    pub const light_yellow: @This() = .{ .r = 0xE0, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const yellow: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const gold: @This() = .{ .r = 0x00, .g = 0xD7, .b = 0xFF, .a = 0xFF };
    pub const light_goldenrod: @This() = .{ .r = 0x82, .g = 0xDD, .b = 0xEE, .a = 0xFF };
    pub const goldenrod: @This() = .{ .r = 0x20, .g = 0xA5, .b = 0xDA, .a = 0xFF };
    pub const dark_goldenrod: @This() = .{ .r = 0x0B, .g = 0x86, .b = 0xB8, .a = 0xFF };
    pub const rosy_brown: @This() = .{ .r = 0x8F, .g = 0x8F, .b = 0xBC, .a = 0xFF };
    pub const indian_red: @This() = .{ .r = 0x5C, .g = 0x5C, .b = 0xCD, .a = 0xFF };
    pub const saddle_brown: @This() = .{ .r = 0x13, .g = 0x45, .b = 0x8B, .a = 0xFF };
    pub const sienna: @This() = .{ .r = 0x2D, .g = 0x52, .b = 0xA0, .a = 0xFF };
    pub const peru: @This() = .{ .r = 0x3F, .g = 0x85, .b = 0xCD, .a = 0xFF };
    pub const burlywood: @This() = .{ .r = 0x87, .g = 0xB8, .b = 0xDE, .a = 0xFF };
    pub const beige: @This() = .{ .r = 0xDC, .g = 0xF5, .b = 0xF5, .a = 0xFF };
    pub const wheat: @This() = .{ .r = 0xB3, .g = 0xDE, .b = 0xF5, .a = 0xFF };
    pub const sandy_brown: @This() = .{ .r = 0x60, .g = 0xA4, .b = 0xF4, .a = 0xFF };
    pub const tan: @This() = .{ .r = 0x8C, .g = 0xB4, .b = 0xD2, .a = 0xFF };
    pub const chocolate: @This() = .{ .r = 0x1E, .g = 0x69, .b = 0xD2, .a = 0xFF };
    pub const firebrick: @This() = .{ .r = 0x22, .g = 0x22, .b = 0xB2, .a = 0xFF };
    pub const brown: @This() = .{ .r = 0x2A, .g = 0x2A, .b = 0xA5, .a = 0xFF };
    pub const dark_salmon: @This() = .{ .r = 0x7A, .g = 0x96, .b = 0xE9, .a = 0xFF };
    pub const salmon: @This() = .{ .r = 0x72, .g = 0x80, .b = 0xFA, .a = 0xFF };
    pub const light_salmon: @This() = .{ .r = 0x7A, .g = 0xA0, .b = 0xFF, .a = 0xFF };
    pub const orange: @This() = .{ .r = 0x00, .g = 0xA5, .b = 0xFF, .a = 0xFF };
    pub const dark_orange: @This() = .{ .r = 0x00, .g = 0x8C, .b = 0xFF, .a = 0xFF };
    pub const coral: @This() = .{ .r = 0x50, .g = 0x7F, .b = 0xFF, .a = 0xFF };
    pub const light_coral: @This() = .{ .r = 0x80, .g = 0x80, .b = 0xF0, .a = 0xFF };
    pub const tomato: @This() = .{ .r = 0x47, .g = 0x63, .b = 0xFF, .a = 0xFF };
    pub const orange_red: @This() = .{ .r = 0x00, .g = 0x45, .b = 0xFF, .a = 0xFF };
    pub const red: @This() = .{ .r = 0x00, .g = 0x00, .b = 0xFF, .a = 0xFF };
    pub const hot_pink: @This() = .{ .r = 0xB4, .g = 0x69, .b = 0xFF, .a = 0xFF };
    pub const deep_pink: @This() = .{ .r = 0x93, .g = 0x14, .b = 0xFF, .a = 0xFF };
    pub const pink: @This() = .{ .r = 0xCB, .g = 0xC0, .b = 0xFF, .a = 0xFF };
    pub const light_pink: @This() = .{ .r = 0xC1, .g = 0xB6, .b = 0xFF, .a = 0xFF };
    pub const pale_violet_red: @This() = .{ .r = 0x93, .g = 0x70, .b = 0xDB, .a = 0xFF };
    pub const maroon: @This() = .{ .r = 0x60, .g = 0x30, .b = 0xB0, .a = 0xFF };
    pub const x11_maroon: @This() = .{ .r = 0x60, .g = 0x30, .b = 0xB0, .a = 0xFF };
    pub const web_maroon: @This() = .{ .r = 0x00, .g = 0x00, .b = 0x80, .a = 0xFF };
    pub const medium_violet_red: @This() = .{ .r = 0x85, .g = 0x15, .b = 0xC7, .a = 0xFF };
    pub const violet_red: @This() = .{ .r = 0x90, .g = 0x20, .b = 0xD0, .a = 0xFF };
    pub const magenta: @This() = .{ .r = 0xFF, .g = 0x00, .b = 0xFF, .a = 0xFF };
    pub const fuchsia: @This() = .{ .r = 0xFF, .g = 0x00, .b = 0xFF, .a = 0xFF };
    pub const violet: @This() = .{ .r = 0xEE, .g = 0x82, .b = 0xEE, .a = 0xFF };
    pub const plum: @This() = .{ .r = 0xDD, .g = 0xA0, .b = 0xDD, .a = 0xFF };
    pub const orchid: @This() = .{ .r = 0xD6, .g = 0x70, .b = 0xDA, .a = 0xFF };
    pub const medium_orchid: @This() = .{ .r = 0xD3, .g = 0x55, .b = 0xBA, .a = 0xFF };
    pub const dark_orchid: @This() = .{ .r = 0xCC, .g = 0x32, .b = 0x99, .a = 0xFF };
    pub const dark_violet: @This() = .{ .r = 0xD3, .g = 0x00, .b = 0x94, .a = 0xFF };
    pub const blue_violet: @This() = .{ .r = 0xE2, .g = 0x2B, .b = 0x8A, .a = 0xFF };
    pub const purple: @This() = .{ .r = 0xF0, .g = 0x20, .b = 0xA0, .a = 0xFF };
    pub const x11_purple: @This() = .{ .r = 0xF0, .g = 0x20, .b = 0xA0, .a = 0xFF };
    pub const web_purple: @This() = .{ .r = 0x80, .g = 0x00, .b = 0x80, .a = 0xFF };
    pub const medium_purple: @This() = .{ .r = 0xDB, .g = 0x70, .b = 0x93, .a = 0xFF };
    pub const thistle: @This() = .{ .r = 0xD8, .g = 0xBF, .b = 0xD8, .a = 0xFF };
    pub const snow1: @This() = .{ .r = 0xFA, .g = 0xFA, .b = 0xFF, .a = 0xFF };
    pub const snow2: @This() = .{ .r = 0xE9, .g = 0xE9, .b = 0xEE, .a = 0xFF };
    pub const snow3: @This() = .{ .r = 0xC9, .g = 0xC9, .b = 0xCD, .a = 0xFF };
    pub const snow4: @This() = .{ .r = 0x89, .g = 0x89, .b = 0x8B, .a = 0xFF };
    pub const seashell1: @This() = .{ .r = 0xEE, .g = 0xF5, .b = 0xFF, .a = 0xFF };
    pub const seashell2: @This() = .{ .r = 0xDE, .g = 0xE5, .b = 0xEE, .a = 0xFF };
    pub const seashell3: @This() = .{ .r = 0xBF, .g = 0xC5, .b = 0xCD, .a = 0xFF };
    pub const seashell4: @This() = .{ .r = 0x82, .g = 0x86, .b = 0x8B, .a = 0xFF };
    pub const antique_white1: @This() = .{ .r = 0xDB, .g = 0xEF, .b = 0xFF, .a = 0xFF };
    pub const antique_white2: @This() = .{ .r = 0xCC, .g = 0xDF, .b = 0xEE, .a = 0xFF };
    pub const antique_white3: @This() = .{ .r = 0xB0, .g = 0xC0, .b = 0xCD, .a = 0xFF };
    pub const antique_white4: @This() = .{ .r = 0x78, .g = 0x83, .b = 0x8B, .a = 0xFF };
    pub const bisque1: @This() = .{ .r = 0xC4, .g = 0xE4, .b = 0xFF, .a = 0xFF };
    pub const bisque2: @This() = .{ .r = 0xB7, .g = 0xD5, .b = 0xEE, .a = 0xFF };
    pub const bisque3: @This() = .{ .r = 0x9E, .g = 0xB7, .b = 0xCD, .a = 0xFF };
    pub const bisque4: @This() = .{ .r = 0x6B, .g = 0x7D, .b = 0x8B, .a = 0xFF };
    pub const peach_puff1: @This() = .{ .r = 0xB9, .g = 0xDA, .b = 0xFF, .a = 0xFF };
    pub const peach_puff2: @This() = .{ .r = 0xAD, .g = 0xCB, .b = 0xEE, .a = 0xFF };
    pub const peach_puff3: @This() = .{ .r = 0x95, .g = 0xAF, .b = 0xCD, .a = 0xFF };
    pub const peach_puff4: @This() = .{ .r = 0x65, .g = 0x77, .b = 0x8B, .a = 0xFF };
    pub const navajo_white1: @This() = .{ .r = 0xAD, .g = 0xDE, .b = 0xFF, .a = 0xFF };
    pub const navajo_white2: @This() = .{ .r = 0xA1, .g = 0xCF, .b = 0xEE, .a = 0xFF };
    pub const navajo_white3: @This() = .{ .r = 0x8B, .g = 0xB3, .b = 0xCD, .a = 0xFF };
    pub const navajo_white4: @This() = .{ .r = 0x5E, .g = 0x79, .b = 0x8B, .a = 0xFF };
    pub const lemon_chiffon1: @This() = .{ .r = 0xCD, .g = 0xFA, .b = 0xFF, .a = 0xFF };
    pub const lemon_chiffon2: @This() = .{ .r = 0xBF, .g = 0xE9, .b = 0xEE, .a = 0xFF };
    pub const lemon_chiffon3: @This() = .{ .r = 0xA5, .g = 0xC9, .b = 0xCD, .a = 0xFF };
    pub const lemon_chiffon4: @This() = .{ .r = 0x70, .g = 0x89, .b = 0x8B, .a = 0xFF };
    pub const cornsilk1: @This() = .{ .r = 0xDC, .g = 0xF8, .b = 0xFF, .a = 0xFF };
    pub const cornsilk2: @This() = .{ .r = 0xCD, .g = 0xE8, .b = 0xEE, .a = 0xFF };
    pub const cornsilk3: @This() = .{ .r = 0xB1, .g = 0xC8, .b = 0xCD, .a = 0xFF };
    pub const cornsilk4: @This() = .{ .r = 0x78, .g = 0x88, .b = 0x8B, .a = 0xFF };
    pub const ivory1: @This() = .{ .r = 0xF0, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const ivory2: @This() = .{ .r = 0xE0, .g = 0xEE, .b = 0xEE, .a = 0xFF };
    pub const ivory3: @This() = .{ .r = 0xC1, .g = 0xCD, .b = 0xCD, .a = 0xFF };
    pub const ivory4: @This() = .{ .r = 0x83, .g = 0x8B, .b = 0x8B, .a = 0xFF };
    pub const honeydew1: @This() = .{ .r = 0xF0, .g = 0xFF, .b = 0xF0, .a = 0xFF };
    pub const honeydew2: @This() = .{ .r = 0xE0, .g = 0xEE, .b = 0xE0, .a = 0xFF };
    pub const honeydew3: @This() = .{ .r = 0xC1, .g = 0xCD, .b = 0xC1, .a = 0xFF };
    pub const honeydew4: @This() = .{ .r = 0x83, .g = 0x8B, .b = 0x83, .a = 0xFF };
    pub const lavender_blush1: @This() = .{ .r = 0xF5, .g = 0xF0, .b = 0xFF, .a = 0xFF };
    pub const lavender_blush2: @This() = .{ .r = 0xE5, .g = 0xE0, .b = 0xEE, .a = 0xFF };
    pub const lavender_blush3: @This() = .{ .r = 0xC5, .g = 0xC1, .b = 0xCD, .a = 0xFF };
    pub const lavender_blush4: @This() = .{ .r = 0x86, .g = 0x83, .b = 0x8B, .a = 0xFF };
    pub const misty_rose1: @This() = .{ .r = 0xE1, .g = 0xE4, .b = 0xFF, .a = 0xFF };
    pub const misty_rose2: @This() = .{ .r = 0xD2, .g = 0xD5, .b = 0xEE, .a = 0xFF };
    pub const misty_rose3: @This() = .{ .r = 0xB5, .g = 0xB7, .b = 0xCD, .a = 0xFF };
    pub const misty_rose4: @This() = .{ .r = 0x7B, .g = 0x7D, .b = 0x8B, .a = 0xFF };
    pub const azure1: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xF0, .a = 0xFF };
    pub const azure2: @This() = .{ .r = 0xEE, .g = 0xEE, .b = 0xE0, .a = 0xFF };
    pub const azure3: @This() = .{ .r = 0xCD, .g = 0xCD, .b = 0xC1, .a = 0xFF };
    pub const azure4: @This() = .{ .r = 0x8B, .g = 0x8B, .b = 0x83, .a = 0xFF };
    pub const slate_blue1: @This() = .{ .r = 0xFF, .g = 0x6F, .b = 0x83, .a = 0xFF };
    pub const slate_blue2: @This() = .{ .r = 0xEE, .g = 0x67, .b = 0x7A, .a = 0xFF };
    pub const slate_blue3: @This() = .{ .r = 0xCD, .g = 0x59, .b = 0x69, .a = 0xFF };
    pub const slate_blue4: @This() = .{ .r = 0x8B, .g = 0x3C, .b = 0x47, .a = 0xFF };
    pub const royal_blue1: @This() = .{ .r = 0xFF, .g = 0x76, .b = 0x48, .a = 0xFF };
    pub const royal_blue2: @This() = .{ .r = 0xEE, .g = 0x6E, .b = 0x43, .a = 0xFF };
    pub const royal_blue3: @This() = .{ .r = 0xCD, .g = 0x5F, .b = 0x3A, .a = 0xFF };
    pub const royal_blue4: @This() = .{ .r = 0x8B, .g = 0x40, .b = 0x27, .a = 0xFF };
    pub const blue1: @This() = .{ .r = 0xFF, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const blue2: @This() = .{ .r = 0xEE, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const blue3: @This() = .{ .r = 0xCD, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const blue4: @This() = .{ .r = 0x8B, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const dodger_blue1: @This() = .{ .r = 0xFF, .g = 0x90, .b = 0x1E, .a = 0xFF };
    pub const dodger_blue2: @This() = .{ .r = 0xEE, .g = 0x86, .b = 0x1C, .a = 0xFF };
    pub const dodger_blue3: @This() = .{ .r = 0xCD, .g = 0x74, .b = 0x18, .a = 0xFF };
    pub const dodger_blue4: @This() = .{ .r = 0x8B, .g = 0x4E, .b = 0x10, .a = 0xFF };
    pub const steel_blue1: @This() = .{ .r = 0xFF, .g = 0xB8, .b = 0x63, .a = 0xFF };
    pub const steel_blue2: @This() = .{ .r = 0xEE, .g = 0xAC, .b = 0x5C, .a = 0xFF };
    pub const steel_blue3: @This() = .{ .r = 0xCD, .g = 0x94, .b = 0x4F, .a = 0xFF };
    pub const steel_blue4: @This() = .{ .r = 0x8B, .g = 0x64, .b = 0x36, .a = 0xFF };
    pub const deep_sky_blue1: @This() = .{ .r = 0xFF, .g = 0xBF, .b = 0x00, .a = 0xFF };
    pub const deep_sky_blue2: @This() = .{ .r = 0xEE, .g = 0xB2, .b = 0x00, .a = 0xFF };
    pub const deep_sky_blue3: @This() = .{ .r = 0xCD, .g = 0x9A, .b = 0x00, .a = 0xFF };
    pub const deep_sky_blue4: @This() = .{ .r = 0x8B, .g = 0x68, .b = 0x00, .a = 0xFF };
    pub const sky_blue1: @This() = .{ .r = 0xFF, .g = 0xCE, .b = 0x87, .a = 0xFF };
    pub const sky_blue2: @This() = .{ .r = 0xEE, .g = 0xC0, .b = 0x7E, .a = 0xFF };
    pub const sky_blue3: @This() = .{ .r = 0xCD, .g = 0xA6, .b = 0x6C, .a = 0xFF };
    pub const sky_blue4: @This() = .{ .r = 0x8B, .g = 0x70, .b = 0x4A, .a = 0xFF };
    pub const light_sky_blue1: @This() = .{ .r = 0xFF, .g = 0xE2, .b = 0xB0, .a = 0xFF };
    pub const light_sky_blue2: @This() = .{ .r = 0xEE, .g = 0xD3, .b = 0xA4, .a = 0xFF };
    pub const light_sky_blue3: @This() = .{ .r = 0xCD, .g = 0xB6, .b = 0x8D, .a = 0xFF };
    pub const light_sky_blue4: @This() = .{ .r = 0x8B, .g = 0x7B, .b = 0x60, .a = 0xFF };
    pub const slate_gray1: @This() = .{ .r = 0xFF, .g = 0xE2, .b = 0xC6, .a = 0xFF };
    pub const slate_gray2: @This() = .{ .r = 0xEE, .g = 0xD3, .b = 0xB9, .a = 0xFF };
    pub const slate_gray3: @This() = .{ .r = 0xCD, .g = 0xB6, .b = 0x9F, .a = 0xFF };
    pub const slate_gray4: @This() = .{ .r = 0x8B, .g = 0x7B, .b = 0x6C, .a = 0xFF };
    pub const light_steel_blue1: @This() = .{ .r = 0xFF, .g = 0xE1, .b = 0xCA, .a = 0xFF };
    pub const light_steel_blue2: @This() = .{ .r = 0xEE, .g = 0xD2, .b = 0xBC, .a = 0xFF };
    pub const light_steel_blue3: @This() = .{ .r = 0xCD, .g = 0xB5, .b = 0xA2, .a = 0xFF };
    pub const light_steel_blue4: @This() = .{ .r = 0x8B, .g = 0x7B, .b = 0x6E, .a = 0xFF };
    pub const light_blue1: @This() = .{ .r = 0xFF, .g = 0xEF, .b = 0xBF, .a = 0xFF };
    pub const light_blue2: @This() = .{ .r = 0xEE, .g = 0xDF, .b = 0xB2, .a = 0xFF };
    pub const light_blue3: @This() = .{ .r = 0xCD, .g = 0xC0, .b = 0x9A, .a = 0xFF };
    pub const light_blue4: @This() = .{ .r = 0x8B, .g = 0x83, .b = 0x68, .a = 0xFF };
    pub const light_cyan1: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xE0, .a = 0xFF };
    pub const light_cyan2: @This() = .{ .r = 0xEE, .g = 0xEE, .b = 0xD1, .a = 0xFF };
    pub const light_cyan3: @This() = .{ .r = 0xCD, .g = 0xCD, .b = 0xB4, .a = 0xFF };
    pub const light_cyan4: @This() = .{ .r = 0x8B, .g = 0x8B, .b = 0x7A, .a = 0xFF };
    pub const pale_turquoise1: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xBB, .a = 0xFF };
    pub const pale_turquoise2: @This() = .{ .r = 0xEE, .g = 0xEE, .b = 0xAE, .a = 0xFF };
    pub const pale_turquoise3: @This() = .{ .r = 0xCD, .g = 0xCD, .b = 0x96, .a = 0xFF };
    pub const pale_turquoise4: @This() = .{ .r = 0x8B, .g = 0x8B, .b = 0x66, .a = 0xFF };
    pub const cadet_blue1: @This() = .{ .r = 0xFF, .g = 0xF5, .b = 0x98, .a = 0xFF };
    pub const cadet_blue2: @This() = .{ .r = 0xEE, .g = 0xE5, .b = 0x8E, .a = 0xFF };
    pub const cadet_blue3: @This() = .{ .r = 0xCD, .g = 0xC5, .b = 0x7A, .a = 0xFF };
    pub const cadet_blue4: @This() = .{ .r = 0x8B, .g = 0x86, .b = 0x53, .a = 0xFF };
    pub const turquoise1: @This() = .{ .r = 0xFF, .g = 0xF5, .b = 0x00, .a = 0xFF };
    pub const turquoise2: @This() = .{ .r = 0xEE, .g = 0xE5, .b = 0x00, .a = 0xFF };
    pub const turquoise3: @This() = .{ .r = 0xCD, .g = 0xC5, .b = 0x00, .a = 0xFF };
    pub const turquoise4: @This() = .{ .r = 0x8B, .g = 0x86, .b = 0x00, .a = 0xFF };
    pub const cyan1: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const cyan2: @This() = .{ .r = 0xEE, .g = 0xEE, .b = 0x00, .a = 0xFF };
    pub const cyan3: @This() = .{ .r = 0xCD, .g = 0xCD, .b = 0x00, .a = 0xFF };
    pub const cyan4: @This() = .{ .r = 0x8B, .g = 0x8B, .b = 0x00, .a = 0xFF };
    pub const dark_slate_gray1: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0x97, .a = 0xFF };
    pub const dark_slate_gray2: @This() = .{ .r = 0xEE, .g = 0xEE, .b = 0x8D, .a = 0xFF };
    pub const dark_slate_gray3: @This() = .{ .r = 0xCD, .g = 0xCD, .b = 0x79, .a = 0xFF };
    pub const dark_slate_gray4: @This() = .{ .r = 0x8B, .g = 0x8B, .b = 0x52, .a = 0xFF };
    pub const aquamarine1: @This() = .{ .r = 0xD4, .g = 0xFF, .b = 0x7F, .a = 0xFF };
    pub const aquamarine2: @This() = .{ .r = 0xC6, .g = 0xEE, .b = 0x76, .a = 0xFF };
    pub const aquamarine3: @This() = .{ .r = 0xAA, .g = 0xCD, .b = 0x66, .a = 0xFF };
    pub const aquamarine4: @This() = .{ .r = 0x74, .g = 0x8B, .b = 0x45, .a = 0xFF };
    pub const dark_sea_green1: @This() = .{ .r = 0xC1, .g = 0xFF, .b = 0xC1, .a = 0xFF };
    pub const dark_sea_green2: @This() = .{ .r = 0xB4, .g = 0xEE, .b = 0xB4, .a = 0xFF };
    pub const dark_sea_green3: @This() = .{ .r = 0x9B, .g = 0xCD, .b = 0x9B, .a = 0xFF };
    pub const dark_sea_green4: @This() = .{ .r = 0x69, .g = 0x8B, .b = 0x69, .a = 0xFF };
    pub const sea_green1: @This() = .{ .r = 0x9F, .g = 0xFF, .b = 0x54, .a = 0xFF };
    pub const sea_green2: @This() = .{ .r = 0x94, .g = 0xEE, .b = 0x4E, .a = 0xFF };
    pub const sea_green3: @This() = .{ .r = 0x80, .g = 0xCD, .b = 0x43, .a = 0xFF };
    pub const sea_green4: @This() = .{ .r = 0x57, .g = 0x8B, .b = 0x2E, .a = 0xFF };
    pub const pale_green1: @This() = .{ .r = 0x9A, .g = 0xFF, .b = 0x9A, .a = 0xFF };
    pub const pale_green2: @This() = .{ .r = 0x90, .g = 0xEE, .b = 0x90, .a = 0xFF };
    pub const pale_green3: @This() = .{ .r = 0x7C, .g = 0xCD, .b = 0x7C, .a = 0xFF };
    pub const pale_green4: @This() = .{ .r = 0x54, .g = 0x8B, .b = 0x54, .a = 0xFF };
    pub const spring_green1: @This() = .{ .r = 0x7F, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const spring_green2: @This() = .{ .r = 0x76, .g = 0xEE, .b = 0x00, .a = 0xFF };
    pub const spring_green3: @This() = .{ .r = 0x66, .g = 0xCD, .b = 0x00, .a = 0xFF };
    pub const spring_green4: @This() = .{ .r = 0x45, .g = 0x8B, .b = 0x00, .a = 0xFF };
    pub const green1: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0x00, .a = 0xFF };
    pub const green2: @This() = .{ .r = 0x00, .g = 0xEE, .b = 0x00, .a = 0xFF };
    pub const green3: @This() = .{ .r = 0x00, .g = 0xCD, .b = 0x00, .a = 0xFF };
    pub const green4: @This() = .{ .r = 0x00, .g = 0x8B, .b = 0x00, .a = 0xFF };
    pub const chartreuse1: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0x7F, .a = 0xFF };
    pub const chartreuse2: @This() = .{ .r = 0x00, .g = 0xEE, .b = 0x76, .a = 0xFF };
    pub const chartreuse3: @This() = .{ .r = 0x00, .g = 0xCD, .b = 0x66, .a = 0xFF };
    pub const chartreuse4: @This() = .{ .r = 0x00, .g = 0x8B, .b = 0x45, .a = 0xFF };
    pub const olive_drab1: @This() = .{ .r = 0x3E, .g = 0xFF, .b = 0xC0, .a = 0xFF };
    pub const olive_drab2: @This() = .{ .r = 0x3A, .g = 0xEE, .b = 0xB3, .a = 0xFF };
    pub const olive_drab3: @This() = .{ .r = 0x32, .g = 0xCD, .b = 0x9A, .a = 0xFF };
    pub const olive_drab4: @This() = .{ .r = 0x22, .g = 0x8B, .b = 0x69, .a = 0xFF };
    pub const dark_olive_green1: @This() = .{ .r = 0x70, .g = 0xFF, .b = 0xCA, .a = 0xFF };
    pub const dark_olive_green2: @This() = .{ .r = 0x68, .g = 0xEE, .b = 0xBC, .a = 0xFF };
    pub const dark_olive_green3: @This() = .{ .r = 0x5A, .g = 0xCD, .b = 0xA2, .a = 0xFF };
    pub const dark_olive_green4: @This() = .{ .r = 0x3D, .g = 0x8B, .b = 0x6E, .a = 0xFF };
    pub const khaki1: @This() = .{ .r = 0x8F, .g = 0xF6, .b = 0xFF, .a = 0xFF };
    pub const khaki2: @This() = .{ .r = 0x85, .g = 0xE6, .b = 0xEE, .a = 0xFF };
    pub const khaki3: @This() = .{ .r = 0x73, .g = 0xC6, .b = 0xCD, .a = 0xFF };
    pub const khaki4: @This() = .{ .r = 0x4E, .g = 0x86, .b = 0x8B, .a = 0xFF };
    pub const light_goldenrod1: @This() = .{ .r = 0x8B, .g = 0xEC, .b = 0xFF, .a = 0xFF };
    pub const light_goldenrod2: @This() = .{ .r = 0x82, .g = 0xDC, .b = 0xEE, .a = 0xFF };
    pub const light_goldenrod3: @This() = .{ .r = 0x70, .g = 0xBE, .b = 0xCD, .a = 0xFF };
    pub const light_goldenrod4: @This() = .{ .r = 0x4C, .g = 0x81, .b = 0x8B, .a = 0xFF };
    pub const light_yellow1: @This() = .{ .r = 0xE0, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const light_yellow2: @This() = .{ .r = 0xD1, .g = 0xEE, .b = 0xEE, .a = 0xFF };
    pub const light_yellow3: @This() = .{ .r = 0xB4, .g = 0xCD, .b = 0xCD, .a = 0xFF };
    pub const light_yellow4: @This() = .{ .r = 0x7A, .g = 0x8B, .b = 0x8B, .a = 0xFF };
    pub const yellow1: @This() = .{ .r = 0x00, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const yellow2: @This() = .{ .r = 0x00, .g = 0xEE, .b = 0xEE, .a = 0xFF };
    pub const yellow3: @This() = .{ .r = 0x00, .g = 0xCD, .b = 0xCD, .a = 0xFF };
    pub const yellow4: @This() = .{ .r = 0x00, .g = 0x8B, .b = 0x8B, .a = 0xFF };
    pub const gold1: @This() = .{ .r = 0x00, .g = 0xD7, .b = 0xFF, .a = 0xFF };
    pub const gold2: @This() = .{ .r = 0x00, .g = 0xC9, .b = 0xEE, .a = 0xFF };
    pub const gold3: @This() = .{ .r = 0x00, .g = 0xAD, .b = 0xCD, .a = 0xFF };
    pub const gold4: @This() = .{ .r = 0x00, .g = 0x75, .b = 0x8B, .a = 0xFF };
    pub const goldenrod1: @This() = .{ .r = 0x25, .g = 0xC1, .b = 0xFF, .a = 0xFF };
    pub const goldenrod2: @This() = .{ .r = 0x22, .g = 0xB4, .b = 0xEE, .a = 0xFF };
    pub const goldenrod3: @This() = .{ .r = 0x1D, .g = 0x9B, .b = 0xCD, .a = 0xFF };
    pub const goldenrod4: @This() = .{ .r = 0x14, .g = 0x69, .b = 0x8B, .a = 0xFF };
    pub const dark_goldenrod1: @This() = .{ .r = 0x0F, .g = 0xB9, .b = 0xFF, .a = 0xFF };
    pub const dark_goldenrod2: @This() = .{ .r = 0x0E, .g = 0xAD, .b = 0xEE, .a = 0xFF };
    pub const dark_goldenrod3: @This() = .{ .r = 0x0C, .g = 0x95, .b = 0xCD, .a = 0xFF };
    pub const dark_goldenrod4: @This() = .{ .r = 0x08, .g = 0x65, .b = 0x8B, .a = 0xFF };
    pub const rosy_brown1: @This() = .{ .r = 0xC1, .g = 0xC1, .b = 0xFF, .a = 0xFF };
    pub const rosy_brown2: @This() = .{ .r = 0xB4, .g = 0xB4, .b = 0xEE, .a = 0xFF };
    pub const rosy_brown3: @This() = .{ .r = 0x9B, .g = 0x9B, .b = 0xCD, .a = 0xFF };
    pub const rosy_brown4: @This() = .{ .r = 0x69, .g = 0x69, .b = 0x8B, .a = 0xFF };
    pub const indian_red1: @This() = .{ .r = 0x6A, .g = 0x6A, .b = 0xFF, .a = 0xFF };
    pub const indian_red2: @This() = .{ .r = 0x63, .g = 0x63, .b = 0xEE, .a = 0xFF };
    pub const indian_red3: @This() = .{ .r = 0x55, .g = 0x55, .b = 0xCD, .a = 0xFF };
    pub const indian_red4: @This() = .{ .r = 0x3A, .g = 0x3A, .b = 0x8B, .a = 0xFF };
    pub const sienna1: @This() = .{ .r = 0x47, .g = 0x82, .b = 0xFF, .a = 0xFF };
    pub const sienna2: @This() = .{ .r = 0x42, .g = 0x79, .b = 0xEE, .a = 0xFF };
    pub const sienna3: @This() = .{ .r = 0x39, .g = 0x68, .b = 0xCD, .a = 0xFF };
    pub const sienna4: @This() = .{ .r = 0x26, .g = 0x47, .b = 0x8B, .a = 0xFF };
    pub const burlywood1: @This() = .{ .r = 0x9B, .g = 0xD3, .b = 0xFF, .a = 0xFF };
    pub const burlywood2: @This() = .{ .r = 0x91, .g = 0xC5, .b = 0xEE, .a = 0xFF };
    pub const burlywood3: @This() = .{ .r = 0x7D, .g = 0xAA, .b = 0xCD, .a = 0xFF };
    pub const burlywood4: @This() = .{ .r = 0x55, .g = 0x73, .b = 0x8B, .a = 0xFF };
    pub const wheat1: @This() = .{ .r = 0xBA, .g = 0xE7, .b = 0xFF, .a = 0xFF };
    pub const wheat2: @This() = .{ .r = 0xAE, .g = 0xD8, .b = 0xEE, .a = 0xFF };
    pub const wheat3: @This() = .{ .r = 0x96, .g = 0xBA, .b = 0xCD, .a = 0xFF };
    pub const wheat4: @This() = .{ .r = 0x66, .g = 0x7E, .b = 0x8B, .a = 0xFF };
    pub const tan1: @This() = .{ .r = 0x4F, .g = 0xA5, .b = 0xFF, .a = 0xFF };
    pub const tan2: @This() = .{ .r = 0x49, .g = 0x9A, .b = 0xEE, .a = 0xFF };
    pub const tan3: @This() = .{ .r = 0x3F, .g = 0x85, .b = 0xCD, .a = 0xFF };
    pub const tan4: @This() = .{ .r = 0x2B, .g = 0x5A, .b = 0x8B, .a = 0xFF };
    pub const chocolate1: @This() = .{ .r = 0x24, .g = 0x7F, .b = 0xFF, .a = 0xFF };
    pub const chocolate2: @This() = .{ .r = 0x21, .g = 0x76, .b = 0xEE, .a = 0xFF };
    pub const chocolate3: @This() = .{ .r = 0x1D, .g = 0x66, .b = 0xCD, .a = 0xFF };
    pub const chocolate4: @This() = .{ .r = 0x13, .g = 0x45, .b = 0x8B, .a = 0xFF };
    pub const firebrick1: @This() = .{ .r = 0x30, .g = 0x30, .b = 0xFF, .a = 0xFF };
    pub const firebrick2: @This() = .{ .r = 0x2C, .g = 0x2C, .b = 0xEE, .a = 0xFF };
    pub const firebrick3: @This() = .{ .r = 0x26, .g = 0x26, .b = 0xCD, .a = 0xFF };
    pub const firebrick4: @This() = .{ .r = 0x1A, .g = 0x1A, .b = 0x8B, .a = 0xFF };
    pub const brown1: @This() = .{ .r = 0x40, .g = 0x40, .b = 0xFF, .a = 0xFF };
    pub const brown2: @This() = .{ .r = 0x3B, .g = 0x3B, .b = 0xEE, .a = 0xFF };
    pub const brown3: @This() = .{ .r = 0x33, .g = 0x33, .b = 0xCD, .a = 0xFF };
    pub const brown4: @This() = .{ .r = 0x23, .g = 0x23, .b = 0x8B, .a = 0xFF };
    pub const salmon1: @This() = .{ .r = 0x69, .g = 0x8C, .b = 0xFF, .a = 0xFF };
    pub const salmon2: @This() = .{ .r = 0x62, .g = 0x82, .b = 0xEE, .a = 0xFF };
    pub const salmon3: @This() = .{ .r = 0x54, .g = 0x70, .b = 0xCD, .a = 0xFF };
    pub const salmon4: @This() = .{ .r = 0x39, .g = 0x4C, .b = 0x8B, .a = 0xFF };
    pub const light_salmon1: @This() = .{ .r = 0x7A, .g = 0xA0, .b = 0xFF, .a = 0xFF };
    pub const light_salmon2: @This() = .{ .r = 0x72, .g = 0x95, .b = 0xEE, .a = 0xFF };
    pub const light_salmon3: @This() = .{ .r = 0x62, .g = 0x81, .b = 0xCD, .a = 0xFF };
    pub const light_salmon4: @This() = .{ .r = 0x42, .g = 0x57, .b = 0x8B, .a = 0xFF };
    pub const orange1: @This() = .{ .r = 0x00, .g = 0xA5, .b = 0xFF, .a = 0xFF };
    pub const orange2: @This() = .{ .r = 0x00, .g = 0x9A, .b = 0xEE, .a = 0xFF };
    pub const orange3: @This() = .{ .r = 0x00, .g = 0x85, .b = 0xCD, .a = 0xFF };
    pub const orange4: @This() = .{ .r = 0x00, .g = 0x5A, .b = 0x8B, .a = 0xFF };
    pub const dark_orange1: @This() = .{ .r = 0x00, .g = 0x7F, .b = 0xFF, .a = 0xFF };
    pub const dark_orange2: @This() = .{ .r = 0x00, .g = 0x76, .b = 0xEE, .a = 0xFF };
    pub const dark_orange3: @This() = .{ .r = 0x00, .g = 0x66, .b = 0xCD, .a = 0xFF };
    pub const dark_orange4: @This() = .{ .r = 0x00, .g = 0x45, .b = 0x8B, .a = 0xFF };
    pub const coral1: @This() = .{ .r = 0x56, .g = 0x72, .b = 0xFF, .a = 0xFF };
    pub const coral2: @This() = .{ .r = 0x50, .g = 0x6A, .b = 0xEE, .a = 0xFF };
    pub const coral3: @This() = .{ .r = 0x45, .g = 0x5B, .b = 0xCD, .a = 0xFF };
    pub const coral4: @This() = .{ .r = 0x2F, .g = 0x3E, .b = 0x8B, .a = 0xFF };
    pub const tomato1: @This() = .{ .r = 0x47, .g = 0x63, .b = 0xFF, .a = 0xFF };
    pub const tomato2: @This() = .{ .r = 0x42, .g = 0x5C, .b = 0xEE, .a = 0xFF };
    pub const tomato3: @This() = .{ .r = 0x39, .g = 0x4F, .b = 0xCD, .a = 0xFF };
    pub const tomato4: @This() = .{ .r = 0x26, .g = 0x36, .b = 0x8B, .a = 0xFF };
    pub const orange_red1: @This() = .{ .r = 0x00, .g = 0x45, .b = 0xFF, .a = 0xFF };
    pub const orange_red2: @This() = .{ .r = 0x00, .g = 0x40, .b = 0xEE, .a = 0xFF };
    pub const orange_red3: @This() = .{ .r = 0x00, .g = 0x37, .b = 0xCD, .a = 0xFF };
    pub const orange_red4: @This() = .{ .r = 0x00, .g = 0x25, .b = 0x8B, .a = 0xFF };
    pub const red1: @This() = .{ .r = 0x00, .g = 0x00, .b = 0xFF, .a = 0xFF };
    pub const red2: @This() = .{ .r = 0x00, .g = 0x00, .b = 0xEE, .a = 0xFF };
    pub const red3: @This() = .{ .r = 0x00, .g = 0x00, .b = 0xCD, .a = 0xFF };
    pub const red4: @This() = .{ .r = 0x00, .g = 0x00, .b = 0x8B, .a = 0xFF };
    pub const deep_pink1: @This() = .{ .r = 0x93, .g = 0x14, .b = 0xFF, .a = 0xFF };
    pub const deep_pink2: @This() = .{ .r = 0x89, .g = 0x12, .b = 0xEE, .a = 0xFF };
    pub const deep_pink3: @This() = .{ .r = 0x76, .g = 0x10, .b = 0xCD, .a = 0xFF };
    pub const deep_pink4: @This() = .{ .r = 0x50, .g = 0x0A, .b = 0x8B, .a = 0xFF };
    pub const hot_pink1: @This() = .{ .r = 0xB4, .g = 0x6E, .b = 0xFF, .a = 0xFF };
    pub const hot_pink2: @This() = .{ .r = 0xA7, .g = 0x6A, .b = 0xEE, .a = 0xFF };
    pub const hot_pink3: @This() = .{ .r = 0x90, .g = 0x60, .b = 0xCD, .a = 0xFF };
    pub const hot_pink4: @This() = .{ .r = 0x62, .g = 0x3A, .b = 0x8B, .a = 0xFF };
    pub const pink1: @This() = .{ .r = 0xC5, .g = 0xB5, .b = 0xFF, .a = 0xFF };
    pub const pink2: @This() = .{ .r = 0xB8, .g = 0xA9, .b = 0xEE, .a = 0xFF };
    pub const pink3: @This() = .{ .r = 0x9E, .g = 0x91, .b = 0xCD, .a = 0xFF };
    pub const pink4: @This() = .{ .r = 0x6C, .g = 0x63, .b = 0x8B, .a = 0xFF };
    pub const light_pink1: @This() = .{ .r = 0xB9, .g = 0xAE, .b = 0xFF, .a = 0xFF };
    pub const light_pink2: @This() = .{ .r = 0xAD, .g = 0xA2, .b = 0xEE, .a = 0xFF };
    pub const light_pink3: @This() = .{ .r = 0x95, .g = 0x8C, .b = 0xCD, .a = 0xFF };
    pub const light_pink4: @This() = .{ .r = 0x65, .g = 0x5F, .b = 0x8B, .a = 0xFF };
    pub const pale_violet_red1: @This() = .{ .r = 0xAB, .g = 0x82, .b = 0xFF, .a = 0xFF };
    pub const pale_violet_red2: @This() = .{ .r = 0x9F, .g = 0x79, .b = 0xEE, .a = 0xFF };
    pub const pale_violet_red3: @This() = .{ .r = 0x89, .g = 0x68, .b = 0xCD, .a = 0xFF };
    pub const pale_violet_red4: @This() = .{ .r = 0x5D, .g = 0x47, .b = 0x8B, .a = 0xFF };
    pub const maroon1: @This() = .{ .r = 0xB3, .g = 0x34, .b = 0xFF, .a = 0xFF };
    pub const maroon2: @This() = .{ .r = 0xA7, .g = 0x30, .b = 0xEE, .a = 0xFF };
    pub const maroon3: @This() = .{ .r = 0x90, .g = 0x29, .b = 0xCD, .a = 0xFF };
    pub const maroon4: @This() = .{ .r = 0x62, .g = 0x1C, .b = 0x8B, .a = 0xFF };
    pub const violet_red1: @This() = .{ .r = 0x96, .g = 0x3E, .b = 0xFF, .a = 0xFF };
    pub const violet_red2: @This() = .{ .r = 0x8C, .g = 0x3A, .b = 0xEE, .a = 0xFF };
    pub const violet_red3: @This() = .{ .r = 0x78, .g = 0x32, .b = 0xCD, .a = 0xFF };
    pub const violet_red4: @This() = .{ .r = 0x52, .g = 0x22, .b = 0x8B, .a = 0xFF };
    pub const magenta1: @This() = .{ .r = 0xFF, .g = 0x00, .b = 0xFF, .a = 0xFF };
    pub const magenta2: @This() = .{ .r = 0xEE, .g = 0x00, .b = 0xEE, .a = 0xFF };
    pub const magenta3: @This() = .{ .r = 0xCD, .g = 0x00, .b = 0xCD, .a = 0xFF };
    pub const magenta4: @This() = .{ .r = 0x8B, .g = 0x00, .b = 0x8B, .a = 0xFF };
    pub const orchid1: @This() = .{ .r = 0xFA, .g = 0x83, .b = 0xFF, .a = 0xFF };
    pub const orchid2: @This() = .{ .r = 0xE9, .g = 0x7A, .b = 0xEE, .a = 0xFF };
    pub const orchid3: @This() = .{ .r = 0xC9, .g = 0x69, .b = 0xCD, .a = 0xFF };
    pub const orchid4: @This() = .{ .r = 0x89, .g = 0x47, .b = 0x8B, .a = 0xFF };
    pub const plum1: @This() = .{ .r = 0xFF, .g = 0xBB, .b = 0xFF, .a = 0xFF };
    pub const plum2: @This() = .{ .r = 0xEE, .g = 0xAE, .b = 0xEE, .a = 0xFF };
    pub const plum3: @This() = .{ .r = 0xCD, .g = 0x96, .b = 0xCD, .a = 0xFF };
    pub const plum4: @This() = .{ .r = 0x8B, .g = 0x66, .b = 0x8B, .a = 0xFF };
    pub const medium_orchid1: @This() = .{ .r = 0xFF, .g = 0x66, .b = 0xE0, .a = 0xFF };
    pub const medium_orchid2: @This() = .{ .r = 0xEE, .g = 0x5F, .b = 0xD1, .a = 0xFF };
    pub const medium_orchid3: @This() = .{ .r = 0xCD, .g = 0x52, .b = 0xB4, .a = 0xFF };
    pub const medium_orchid4: @This() = .{ .r = 0x8B, .g = 0x37, .b = 0x7A, .a = 0xFF };
    pub const dark_orchid1: @This() = .{ .r = 0xFF, .g = 0x3E, .b = 0xBF, .a = 0xFF };
    pub const dark_orchid2: @This() = .{ .r = 0xEE, .g = 0x3A, .b = 0xB2, .a = 0xFF };
    pub const dark_orchid3: @This() = .{ .r = 0xCD, .g = 0x32, .b = 0x9A, .a = 0xFF };
    pub const dark_orchid4: @This() = .{ .r = 0x8B, .g = 0x22, .b = 0x68, .a = 0xFF };
    pub const purple1: @This() = .{ .r = 0xFF, .g = 0x30, .b = 0x9B, .a = 0xFF };
    pub const purple2: @This() = .{ .r = 0xEE, .g = 0x2C, .b = 0x91, .a = 0xFF };
    pub const purple3: @This() = .{ .r = 0xCD, .g = 0x26, .b = 0x7D, .a = 0xFF };
    pub const purple4: @This() = .{ .r = 0x8B, .g = 0x1A, .b = 0x55, .a = 0xFF };
    pub const medium_purple1: @This() = .{ .r = 0xFF, .g = 0x82, .b = 0xAB, .a = 0xFF };
    pub const medium_purple2: @This() = .{ .r = 0xEE, .g = 0x79, .b = 0x9F, .a = 0xFF };
    pub const medium_purple3: @This() = .{ .r = 0xCD, .g = 0x68, .b = 0x89, .a = 0xFF };
    pub const medium_purple4: @This() = .{ .r = 0x8B, .g = 0x47, .b = 0x5D, .a = 0xFF };
    pub const thistle1: @This() = .{ .r = 0xFF, .g = 0xE1, .b = 0xFF, .a = 0xFF };
    pub const thistle2: @This() = .{ .r = 0xEE, .g = 0xD2, .b = 0xEE, .a = 0xFF };
    pub const thistle3: @This() = .{ .r = 0xCD, .g = 0xB5, .b = 0xCD, .a = 0xFF };
    pub const thistle4: @This() = .{ .r = 0x8B, .g = 0x7B, .b = 0x8B, .a = 0xFF };
    pub const gray0: @This() = .{ .r = 0x00, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const grey0: @This() = .{ .r = 0x00, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const gray1: @This() = .{ .r = 0x03, .g = 0x03, .b = 0x03, .a = 0xFF };
    pub const grey1: @This() = .{ .r = 0x03, .g = 0x03, .b = 0x03, .a = 0xFF };
    pub const gray2: @This() = .{ .r = 0x05, .g = 0x05, .b = 0x05, .a = 0xFF };
    pub const grey2: @This() = .{ .r = 0x05, .g = 0x05, .b = 0x05, .a = 0xFF };
    pub const gray3: @This() = .{ .r = 0x08, .g = 0x08, .b = 0x08, .a = 0xFF };
    pub const grey3: @This() = .{ .r = 0x08, .g = 0x08, .b = 0x08, .a = 0xFF };
    pub const gray4: @This() = .{ .r = 0x0A, .g = 0x0A, .b = 0x0A, .a = 0xFF };
    pub const grey4: @This() = .{ .r = 0x0A, .g = 0x0A, .b = 0x0A, .a = 0xFF };
    pub const gray5: @This() = .{ .r = 0x0D, .g = 0x0D, .b = 0x0D, .a = 0xFF };
    pub const grey5: @This() = .{ .r = 0x0D, .g = 0x0D, .b = 0x0D, .a = 0xFF };
    pub const gray6: @This() = .{ .r = 0x0F, .g = 0x0F, .b = 0x0F, .a = 0xFF };
    pub const grey6: @This() = .{ .r = 0x0F, .g = 0x0F, .b = 0x0F, .a = 0xFF };
    pub const gray7: @This() = .{ .r = 0x12, .g = 0x12, .b = 0x12, .a = 0xFF };
    pub const grey7: @This() = .{ .r = 0x12, .g = 0x12, .b = 0x12, .a = 0xFF };
    pub const gray8: @This() = .{ .r = 0x14, .g = 0x14, .b = 0x14, .a = 0xFF };
    pub const grey8: @This() = .{ .r = 0x14, .g = 0x14, .b = 0x14, .a = 0xFF };
    pub const gray9: @This() = .{ .r = 0x17, .g = 0x17, .b = 0x17, .a = 0xFF };
    pub const grey9: @This() = .{ .r = 0x17, .g = 0x17, .b = 0x17, .a = 0xFF };
    pub const gray10: @This() = .{ .r = 0x1A, .g = 0x1A, .b = 0x1A, .a = 0xFF };
    pub const grey10: @This() = .{ .r = 0x1A, .g = 0x1A, .b = 0x1A, .a = 0xFF };
    pub const gray11: @This() = .{ .r = 0x1C, .g = 0x1C, .b = 0x1C, .a = 0xFF };
    pub const grey11: @This() = .{ .r = 0x1C, .g = 0x1C, .b = 0x1C, .a = 0xFF };
    pub const gray12: @This() = .{ .r = 0x1F, .g = 0x1F, .b = 0x1F, .a = 0xFF };
    pub const grey12: @This() = .{ .r = 0x1F, .g = 0x1F, .b = 0x1F, .a = 0xFF };
    pub const gray13: @This() = .{ .r = 0x21, .g = 0x21, .b = 0x21, .a = 0xFF };
    pub const grey13: @This() = .{ .r = 0x21, .g = 0x21, .b = 0x21, .a = 0xFF };
    pub const gray14: @This() = .{ .r = 0x24, .g = 0x24, .b = 0x24, .a = 0xFF };
    pub const grey14: @This() = .{ .r = 0x24, .g = 0x24, .b = 0x24, .a = 0xFF };
    pub const gray15: @This() = .{ .r = 0x26, .g = 0x26, .b = 0x26, .a = 0xFF };
    pub const grey15: @This() = .{ .r = 0x26, .g = 0x26, .b = 0x26, .a = 0xFF };
    pub const gray16: @This() = .{ .r = 0x29, .g = 0x29, .b = 0x29, .a = 0xFF };
    pub const grey16: @This() = .{ .r = 0x29, .g = 0x29, .b = 0x29, .a = 0xFF };
    pub const gray17: @This() = .{ .r = 0x2B, .g = 0x2B, .b = 0x2B, .a = 0xFF };
    pub const grey17: @This() = .{ .r = 0x2B, .g = 0x2B, .b = 0x2B, .a = 0xFF };
    pub const gray18: @This() = .{ .r = 0x2E, .g = 0x2E, .b = 0x2E, .a = 0xFF };
    pub const grey18: @This() = .{ .r = 0x2E, .g = 0x2E, .b = 0x2E, .a = 0xFF };
    pub const gray19: @This() = .{ .r = 0x30, .g = 0x30, .b = 0x30, .a = 0xFF };
    pub const grey19: @This() = .{ .r = 0x30, .g = 0x30, .b = 0x30, .a = 0xFF };
    pub const gray20: @This() = .{ .r = 0x33, .g = 0x33, .b = 0x33, .a = 0xFF };
    pub const grey20: @This() = .{ .r = 0x33, .g = 0x33, .b = 0x33, .a = 0xFF };
    pub const gray21: @This() = .{ .r = 0x36, .g = 0x36, .b = 0x36, .a = 0xFF };
    pub const grey21: @This() = .{ .r = 0x36, .g = 0x36, .b = 0x36, .a = 0xFF };
    pub const gray22: @This() = .{ .r = 0x38, .g = 0x38, .b = 0x38, .a = 0xFF };
    pub const grey22: @This() = .{ .r = 0x38, .g = 0x38, .b = 0x38, .a = 0xFF };
    pub const gray23: @This() = .{ .r = 0x3B, .g = 0x3B, .b = 0x3B, .a = 0xFF };
    pub const grey23: @This() = .{ .r = 0x3B, .g = 0x3B, .b = 0x3B, .a = 0xFF };
    pub const gray24: @This() = .{ .r = 0x3D, .g = 0x3D, .b = 0x3D, .a = 0xFF };
    pub const grey24: @This() = .{ .r = 0x3D, .g = 0x3D, .b = 0x3D, .a = 0xFF };
    pub const gray25: @This() = .{ .r = 0x40, .g = 0x40, .b = 0x40, .a = 0xFF };
    pub const grey25: @This() = .{ .r = 0x40, .g = 0x40, .b = 0x40, .a = 0xFF };
    pub const gray26: @This() = .{ .r = 0x42, .g = 0x42, .b = 0x42, .a = 0xFF };
    pub const grey26: @This() = .{ .r = 0x42, .g = 0x42, .b = 0x42, .a = 0xFF };
    pub const gray27: @This() = .{ .r = 0x45, .g = 0x45, .b = 0x45, .a = 0xFF };
    pub const grey27: @This() = .{ .r = 0x45, .g = 0x45, .b = 0x45, .a = 0xFF };
    pub const gray28: @This() = .{ .r = 0x47, .g = 0x47, .b = 0x47, .a = 0xFF };
    pub const grey28: @This() = .{ .r = 0x47, .g = 0x47, .b = 0x47, .a = 0xFF };
    pub const gray29: @This() = .{ .r = 0x4A, .g = 0x4A, .b = 0x4A, .a = 0xFF };
    pub const grey29: @This() = .{ .r = 0x4A, .g = 0x4A, .b = 0x4A, .a = 0xFF };
    pub const gray30: @This() = .{ .r = 0x4D, .g = 0x4D, .b = 0x4D, .a = 0xFF };
    pub const grey30: @This() = .{ .r = 0x4D, .g = 0x4D, .b = 0x4D, .a = 0xFF };
    pub const gray31: @This() = .{ .r = 0x4F, .g = 0x4F, .b = 0x4F, .a = 0xFF };
    pub const grey31: @This() = .{ .r = 0x4F, .g = 0x4F, .b = 0x4F, .a = 0xFF };
    pub const gray32: @This() = .{ .r = 0x52, .g = 0x52, .b = 0x52, .a = 0xFF };
    pub const grey32: @This() = .{ .r = 0x52, .g = 0x52, .b = 0x52, .a = 0xFF };
    pub const gray33: @This() = .{ .r = 0x54, .g = 0x54, .b = 0x54, .a = 0xFF };
    pub const grey33: @This() = .{ .r = 0x54, .g = 0x54, .b = 0x54, .a = 0xFF };
    pub const gray34: @This() = .{ .r = 0x57, .g = 0x57, .b = 0x57, .a = 0xFF };
    pub const grey34: @This() = .{ .r = 0x57, .g = 0x57, .b = 0x57, .a = 0xFF };
    pub const gray35: @This() = .{ .r = 0x59, .g = 0x59, .b = 0x59, .a = 0xFF };
    pub const grey35: @This() = .{ .r = 0x59, .g = 0x59, .b = 0x59, .a = 0xFF };
    pub const gray36: @This() = .{ .r = 0x5C, .g = 0x5C, .b = 0x5C, .a = 0xFF };
    pub const grey36: @This() = .{ .r = 0x5C, .g = 0x5C, .b = 0x5C, .a = 0xFF };
    pub const gray37: @This() = .{ .r = 0x5E, .g = 0x5E, .b = 0x5E, .a = 0xFF };
    pub const grey37: @This() = .{ .r = 0x5E, .g = 0x5E, .b = 0x5E, .a = 0xFF };
    pub const gray38: @This() = .{ .r = 0x61, .g = 0x61, .b = 0x61, .a = 0xFF };
    pub const grey38: @This() = .{ .r = 0x61, .g = 0x61, .b = 0x61, .a = 0xFF };
    pub const gray39: @This() = .{ .r = 0x63, .g = 0x63, .b = 0x63, .a = 0xFF };
    pub const grey39: @This() = .{ .r = 0x63, .g = 0x63, .b = 0x63, .a = 0xFF };
    pub const gray40: @This() = .{ .r = 0x66, .g = 0x66, .b = 0x66, .a = 0xFF };
    pub const grey40: @This() = .{ .r = 0x66, .g = 0x66, .b = 0x66, .a = 0xFF };
    pub const gray41: @This() = .{ .r = 0x69, .g = 0x69, .b = 0x69, .a = 0xFF };
    pub const grey41: @This() = .{ .r = 0x69, .g = 0x69, .b = 0x69, .a = 0xFF };
    pub const gray42: @This() = .{ .r = 0x6B, .g = 0x6B, .b = 0x6B, .a = 0xFF };
    pub const grey42: @This() = .{ .r = 0x6B, .g = 0x6B, .b = 0x6B, .a = 0xFF };
    pub const gray43: @This() = .{ .r = 0x6E, .g = 0x6E, .b = 0x6E, .a = 0xFF };
    pub const grey43: @This() = .{ .r = 0x6E, .g = 0x6E, .b = 0x6E, .a = 0xFF };
    pub const gray44: @This() = .{ .r = 0x70, .g = 0x70, .b = 0x70, .a = 0xFF };
    pub const grey44: @This() = .{ .r = 0x70, .g = 0x70, .b = 0x70, .a = 0xFF };
    pub const gray45: @This() = .{ .r = 0x73, .g = 0x73, .b = 0x73, .a = 0xFF };
    pub const grey45: @This() = .{ .r = 0x73, .g = 0x73, .b = 0x73, .a = 0xFF };
    pub const gray46: @This() = .{ .r = 0x75, .g = 0x75, .b = 0x75, .a = 0xFF };
    pub const grey46: @This() = .{ .r = 0x75, .g = 0x75, .b = 0x75, .a = 0xFF };
    pub const gray47: @This() = .{ .r = 0x78, .g = 0x78, .b = 0x78, .a = 0xFF };
    pub const grey47: @This() = .{ .r = 0x78, .g = 0x78, .b = 0x78, .a = 0xFF };
    pub const gray48: @This() = .{ .r = 0x7A, .g = 0x7A, .b = 0x7A, .a = 0xFF };
    pub const grey48: @This() = .{ .r = 0x7A, .g = 0x7A, .b = 0x7A, .a = 0xFF };
    pub const gray49: @This() = .{ .r = 0x7D, .g = 0x7D, .b = 0x7D, .a = 0xFF };
    pub const grey49: @This() = .{ .r = 0x7D, .g = 0x7D, .b = 0x7D, .a = 0xFF };
    pub const gray50: @This() = .{ .r = 0x7F, .g = 0x7F, .b = 0x7F, .a = 0xFF };
    pub const grey50: @This() = .{ .r = 0x7F, .g = 0x7F, .b = 0x7F, .a = 0xFF };
    pub const gray51: @This() = .{ .r = 0x82, .g = 0x82, .b = 0x82, .a = 0xFF };
    pub const grey51: @This() = .{ .r = 0x82, .g = 0x82, .b = 0x82, .a = 0xFF };
    pub const gray52: @This() = .{ .r = 0x85, .g = 0x85, .b = 0x85, .a = 0xFF };
    pub const grey52: @This() = .{ .r = 0x85, .g = 0x85, .b = 0x85, .a = 0xFF };
    pub const gray53: @This() = .{ .r = 0x87, .g = 0x87, .b = 0x87, .a = 0xFF };
    pub const grey53: @This() = .{ .r = 0x87, .g = 0x87, .b = 0x87, .a = 0xFF };
    pub const gray54: @This() = .{ .r = 0x8A, .g = 0x8A, .b = 0x8A, .a = 0xFF };
    pub const grey54: @This() = .{ .r = 0x8A, .g = 0x8A, .b = 0x8A, .a = 0xFF };
    pub const gray55: @This() = .{ .r = 0x8C, .g = 0x8C, .b = 0x8C, .a = 0xFF };
    pub const grey55: @This() = .{ .r = 0x8C, .g = 0x8C, .b = 0x8C, .a = 0xFF };
    pub const gray56: @This() = .{ .r = 0x8F, .g = 0x8F, .b = 0x8F, .a = 0xFF };
    pub const grey56: @This() = .{ .r = 0x8F, .g = 0x8F, .b = 0x8F, .a = 0xFF };
    pub const gray57: @This() = .{ .r = 0x91, .g = 0x91, .b = 0x91, .a = 0xFF };
    pub const grey57: @This() = .{ .r = 0x91, .g = 0x91, .b = 0x91, .a = 0xFF };
    pub const gray58: @This() = .{ .r = 0x94, .g = 0x94, .b = 0x94, .a = 0xFF };
    pub const grey58: @This() = .{ .r = 0x94, .g = 0x94, .b = 0x94, .a = 0xFF };
    pub const gray59: @This() = .{ .r = 0x96, .g = 0x96, .b = 0x96, .a = 0xFF };
    pub const grey59: @This() = .{ .r = 0x96, .g = 0x96, .b = 0x96, .a = 0xFF };
    pub const gray60: @This() = .{ .r = 0x99, .g = 0x99, .b = 0x99, .a = 0xFF };
    pub const grey60: @This() = .{ .r = 0x99, .g = 0x99, .b = 0x99, .a = 0xFF };
    pub const gray61: @This() = .{ .r = 0x9C, .g = 0x9C, .b = 0x9C, .a = 0xFF };
    pub const grey61: @This() = .{ .r = 0x9C, .g = 0x9C, .b = 0x9C, .a = 0xFF };
    pub const gray62: @This() = .{ .r = 0x9E, .g = 0x9E, .b = 0x9E, .a = 0xFF };
    pub const grey62: @This() = .{ .r = 0x9E, .g = 0x9E, .b = 0x9E, .a = 0xFF };
    pub const gray63: @This() = .{ .r = 0xA1, .g = 0xA1, .b = 0xA1, .a = 0xFF };
    pub const grey63: @This() = .{ .r = 0xA1, .g = 0xA1, .b = 0xA1, .a = 0xFF };
    pub const gray64: @This() = .{ .r = 0xA3, .g = 0xA3, .b = 0xA3, .a = 0xFF };
    pub const grey64: @This() = .{ .r = 0xA3, .g = 0xA3, .b = 0xA3, .a = 0xFF };
    pub const gray65: @This() = .{ .r = 0xA6, .g = 0xA6, .b = 0xA6, .a = 0xFF };
    pub const grey65: @This() = .{ .r = 0xA6, .g = 0xA6, .b = 0xA6, .a = 0xFF };
    pub const gray66: @This() = .{ .r = 0xA8, .g = 0xA8, .b = 0xA8, .a = 0xFF };
    pub const grey66: @This() = .{ .r = 0xA8, .g = 0xA8, .b = 0xA8, .a = 0xFF };
    pub const gray67: @This() = .{ .r = 0xAB, .g = 0xAB, .b = 0xAB, .a = 0xFF };
    pub const grey67: @This() = .{ .r = 0xAB, .g = 0xAB, .b = 0xAB, .a = 0xFF };
    pub const gray68: @This() = .{ .r = 0xAD, .g = 0xAD, .b = 0xAD, .a = 0xFF };
    pub const grey68: @This() = .{ .r = 0xAD, .g = 0xAD, .b = 0xAD, .a = 0xFF };
    pub const gray69: @This() = .{ .r = 0xB0, .g = 0xB0, .b = 0xB0, .a = 0xFF };
    pub const grey69: @This() = .{ .r = 0xB0, .g = 0xB0, .b = 0xB0, .a = 0xFF };
    pub const gray70: @This() = .{ .r = 0xB3, .g = 0xB3, .b = 0xB3, .a = 0xFF };
    pub const grey70: @This() = .{ .r = 0xB3, .g = 0xB3, .b = 0xB3, .a = 0xFF };
    pub const gray71: @This() = .{ .r = 0xB5, .g = 0xB5, .b = 0xB5, .a = 0xFF };
    pub const grey71: @This() = .{ .r = 0xB5, .g = 0xB5, .b = 0xB5, .a = 0xFF };
    pub const gray72: @This() = .{ .r = 0xB8, .g = 0xB8, .b = 0xB8, .a = 0xFF };
    pub const grey72: @This() = .{ .r = 0xB8, .g = 0xB8, .b = 0xB8, .a = 0xFF };
    pub const gray73: @This() = .{ .r = 0xBA, .g = 0xBA, .b = 0xBA, .a = 0xFF };
    pub const grey73: @This() = .{ .r = 0xBA, .g = 0xBA, .b = 0xBA, .a = 0xFF };
    pub const gray74: @This() = .{ .r = 0xBD, .g = 0xBD, .b = 0xBD, .a = 0xFF };
    pub const grey74: @This() = .{ .r = 0xBD, .g = 0xBD, .b = 0xBD, .a = 0xFF };
    pub const gray75: @This() = .{ .r = 0xBF, .g = 0xBF, .b = 0xBF, .a = 0xFF };
    pub const grey75: @This() = .{ .r = 0xBF, .g = 0xBF, .b = 0xBF, .a = 0xFF };
    pub const gray76: @This() = .{ .r = 0xC2, .g = 0xC2, .b = 0xC2, .a = 0xFF };
    pub const grey76: @This() = .{ .r = 0xC2, .g = 0xC2, .b = 0xC2, .a = 0xFF };
    pub const gray77: @This() = .{ .r = 0xC4, .g = 0xC4, .b = 0xC4, .a = 0xFF };
    pub const grey77: @This() = .{ .r = 0xC4, .g = 0xC4, .b = 0xC4, .a = 0xFF };
    pub const gray78: @This() = .{ .r = 0xC7, .g = 0xC7, .b = 0xC7, .a = 0xFF };
    pub const grey78: @This() = .{ .r = 0xC7, .g = 0xC7, .b = 0xC7, .a = 0xFF };
    pub const gray79: @This() = .{ .r = 0xC9, .g = 0xC9, .b = 0xC9, .a = 0xFF };
    pub const grey79: @This() = .{ .r = 0xC9, .g = 0xC9, .b = 0xC9, .a = 0xFF };
    pub const gray80: @This() = .{ .r = 0xCC, .g = 0xCC, .b = 0xCC, .a = 0xFF };
    pub const grey80: @This() = .{ .r = 0xCC, .g = 0xCC, .b = 0xCC, .a = 0xFF };
    pub const gray81: @This() = .{ .r = 0xCF, .g = 0xCF, .b = 0xCF, .a = 0xFF };
    pub const grey81: @This() = .{ .r = 0xCF, .g = 0xCF, .b = 0xCF, .a = 0xFF };
    pub const gray82: @This() = .{ .r = 0xD1, .g = 0xD1, .b = 0xD1, .a = 0xFF };
    pub const grey82: @This() = .{ .r = 0xD1, .g = 0xD1, .b = 0xD1, .a = 0xFF };
    pub const gray83: @This() = .{ .r = 0xD4, .g = 0xD4, .b = 0xD4, .a = 0xFF };
    pub const grey83: @This() = .{ .r = 0xD4, .g = 0xD4, .b = 0xD4, .a = 0xFF };
    pub const gray84: @This() = .{ .r = 0xD6, .g = 0xD6, .b = 0xD6, .a = 0xFF };
    pub const grey84: @This() = .{ .r = 0xD6, .g = 0xD6, .b = 0xD6, .a = 0xFF };
    pub const gray85: @This() = .{ .r = 0xD9, .g = 0xD9, .b = 0xD9, .a = 0xFF };
    pub const grey85: @This() = .{ .r = 0xD9, .g = 0xD9, .b = 0xD9, .a = 0xFF };
    pub const gray86: @This() = .{ .r = 0xDB, .g = 0xDB, .b = 0xDB, .a = 0xFF };
    pub const grey86: @This() = .{ .r = 0xDB, .g = 0xDB, .b = 0xDB, .a = 0xFF };
    pub const gray87: @This() = .{ .r = 0xDE, .g = 0xDE, .b = 0xDE, .a = 0xFF };
    pub const grey87: @This() = .{ .r = 0xDE, .g = 0xDE, .b = 0xDE, .a = 0xFF };
    pub const gray88: @This() = .{ .r = 0xE0, .g = 0xE0, .b = 0xE0, .a = 0xFF };
    pub const grey88: @This() = .{ .r = 0xE0, .g = 0xE0, .b = 0xE0, .a = 0xFF };
    pub const gray89: @This() = .{ .r = 0xE3, .g = 0xE3, .b = 0xE3, .a = 0xFF };
    pub const grey89: @This() = .{ .r = 0xE3, .g = 0xE3, .b = 0xE3, .a = 0xFF };
    pub const gray90: @This() = .{ .r = 0xE5, .g = 0xE5, .b = 0xE5, .a = 0xFF };
    pub const grey90: @This() = .{ .r = 0xE5, .g = 0xE5, .b = 0xE5, .a = 0xFF };
    pub const gray91: @This() = .{ .r = 0xE8, .g = 0xE8, .b = 0xE8, .a = 0xFF };
    pub const grey91: @This() = .{ .r = 0xE8, .g = 0xE8, .b = 0xE8, .a = 0xFF };
    pub const gray92: @This() = .{ .r = 0xEB, .g = 0xEB, .b = 0xEB, .a = 0xFF };
    pub const grey92: @This() = .{ .r = 0xEB, .g = 0xEB, .b = 0xEB, .a = 0xFF };
    pub const gray93: @This() = .{ .r = 0xED, .g = 0xED, .b = 0xED, .a = 0xFF };
    pub const grey93: @This() = .{ .r = 0xED, .g = 0xED, .b = 0xED, .a = 0xFF };
    pub const gray94: @This() = .{ .r = 0xF0, .g = 0xF0, .b = 0xF0, .a = 0xFF };
    pub const grey94: @This() = .{ .r = 0xF0, .g = 0xF0, .b = 0xF0, .a = 0xFF };
    pub const gray95: @This() = .{ .r = 0xF2, .g = 0xF2, .b = 0xF2, .a = 0xFF };
    pub const grey95: @This() = .{ .r = 0xF2, .g = 0xF2, .b = 0xF2, .a = 0xFF };
    pub const gray96: @This() = .{ .r = 0xF5, .g = 0xF5, .b = 0xF5, .a = 0xFF };
    pub const grey96: @This() = .{ .r = 0xF5, .g = 0xF5, .b = 0xF5, .a = 0xFF };
    pub const gray97: @This() = .{ .r = 0xF7, .g = 0xF7, .b = 0xF7, .a = 0xFF };
    pub const grey97: @This() = .{ .r = 0xF7, .g = 0xF7, .b = 0xF7, .a = 0xFF };
    pub const gray98: @This() = .{ .r = 0xFA, .g = 0xFA, .b = 0xFA, .a = 0xFF };
    pub const grey98: @This() = .{ .r = 0xFA, .g = 0xFA, .b = 0xFA, .a = 0xFF };
    pub const gray99: @This() = .{ .r = 0xFC, .g = 0xFC, .b = 0xFC, .a = 0xFF };
    pub const grey99: @This() = .{ .r = 0xFC, .g = 0xFC, .b = 0xFC, .a = 0xFF };
    pub const gray100: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const grey100: @This() = .{ .r = 0xFF, .g = 0xFF, .b = 0xFF, .a = 0xFF };
    pub const dark_grey: @This() = .{ .r = 0xA9, .g = 0xA9, .b = 0xA9, .a = 0xFF };
    pub const dark_gray: @This() = .{ .r = 0xA9, .g = 0xA9, .b = 0xA9, .a = 0xFF };
    pub const dark_blue: @This() = .{ .r = 0x8B, .g = 0x00, .b = 0x00, .a = 0xFF };
    pub const dark_cyan: @This() = .{ .r = 0x8B, .g = 0x8B, .b = 0x00, .a = 0xFF };
    pub const dark_magenta: @This() = .{ .r = 0x8B, .g = 0x00, .b = 0x8B, .a = 0xFF };
    pub const dark_red: @This() = .{ .r = 0x00, .g = 0x00, .b = 0x8B, .a = 0xFF };
    pub const light_green: @This() = .{ .r = 0x90, .g = 0xEE, .b = 0x90, .a = 0xFF };
    pub const crimson: @This() = .{ .r = 0x3C, .g = 0x14, .b = 0xDC, .a = 0xFF };
    pub const indigo: @This() = .{ .r = 0x82, .g = 0x00, .b = 0x4B, .a = 0xFF };
    pub const olive: @This() = .{ .r = 0x00, .g = 0x80, .b = 0x80, .a = 0xFF };
    pub const rebecca_purple: @This() = .{ .r = 0x99, .g = 0x33, .b = 0x66, .a = 0xFF };
    pub const silver: @This() = .{ .r = 0xC0, .g = 0xC0, .b = 0xC0, .a = 0xFF };
    pub const teal: @This() = .{ .r = 0x80, .g = 0x80, .b = 0x00, .a = 0xFF };
};
